### ISSUE TITLE
Remove GCS bucket requirement for TPUEstimator

### ISSUE THREAD

**Issue by vbogach** [tensorflow/adanet#109]
Currently Adanet in Google Colab requires an GCS bucket. It would be neat to be able to use locally stored data instead.

**Comment by cweill** [comment]
@EugenHotaj: Is there a way we can use GCE TPU without a GCS bucket?

**Comment by EugenHotaj** [comment]
AFAIK it's not possible to use Cloud TPUs with data stored on your local machine. Since TPUs run on Cloud servers, they'd have no way to interact with your local data. 

Closing this out as infeasible. Please feel free to reopen if there is a way to use your local data and we'll modify the Colab to do this instead!
